/**
 * GOA GUIDE — Data Layer
 * ========================
 * Add new categories by following the existing pattern.
 * Each category needs: icon, title, color, items[]
 * Each item can have: name, area, desc, lat, lng, tags[], price, where, shelfLife
 * Enriched fields: timeToSpend, rating (1-5), popularity (high/medium/low), bestTime
 *
 * The app auto-discovers categories — just add a new key and it appears.
 */

const GOA_DATA = {
  beaches: {
    icon: "🏖️",
    title: "Beaches",
    color: "#0EA5E9",
    items: [
      { name: "Palolem Beach", area: "South", desc: "Crescent-shaped, calm waters, dolphin spotting. One of Goa's most beautiful.", lat: 15.0100, lng: 74.0230, tags: ["swimming", "scenic", "kayaking"], timeToSpend: "2-3 hours", rating: 4.5, popularity: "high", bestTime: "Oct-Mar, morning or sunset" },
      { name: "Butterfly Beach", area: "South", desc: "Only accessible by boat from Palolem. Secluded paradise, dolphins frequent.", lat: 15.0020, lng: 74.0130, tags: ["secluded", "boat-access", "dolphins"], timeToSpend: "1-2 hours", rating: 4.0, popularity: "medium", bestTime: "Nov-Mar, morning to early afternoon" },
      { name: "Cola Beach", area: "South", desc: "Hidden lagoon meets the sea. Freshwater lagoon perfect for swimming. Dramatic cliff approach.", lat: 15.0350, lng: 74.0000, tags: ["lagoon", "secluded", "scenic"], timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Oct-Mar, any time" },
      { name: "Agonda Beach", area: "South", desc: "Long, quiet stretch. Olive Ridley turtle nesting site. Less touristy than Palolem.", lat: 15.0440, lng: 73.9870, tags: ["quiet", "turtles", "long-walk"], timeToSpend: "2-4 hours", rating: 4.5, popularity: "medium", bestTime: "Oct-Mar for calm waters" },
      { name: "Cabo de Rama Beach", area: "South", desc: "Below the ancient fort. Rocky, wild, barely any tourists. Real adventure beach.", lat: 15.0890, lng: 73.9280, tags: ["secluded", "adventure", "fort-nearby"], timeToSpend: "1-2 hours", rating: 3.5, popularity: "low", bestTime: "Nov-Feb, morning" },
      { name: "Vagator Beach", area: "North", desc: "Red cliffs, Chapora Fort above. Famous for trance music scene and dramatic landscape.", lat: 15.5970, lng: 73.7360, tags: ["scenic", "cliffs", "party-history"], timeToSpend: "2-3 hours", rating: 4.2, popularity: "high", bestTime: "Nov-Mar, sunset" },
      { name: "Anjuna Beach", area: "North", desc: "Flea market on Wednesdays. Birthplace of Goa's hippie culture in the 60s.", lat: 15.5730, lng: 73.7410, tags: ["flea-market", "hippie-history", "lively"], timeToSpend: "2-3 hours", rating: 4.0, popularity: "high", bestTime: "Nov-Mar, evening for nightlife" },
      { name: "Morjim Beach", area: "North", desc: "Olive Ridley turtle nesting. Russian expat scene. Quieter stretch of North Goa.", lat: 15.6290, lng: 73.7280, tags: ["turtles", "quiet", "nature"], timeToSpend: "2-3 hours", rating: 4.4, popularity: "medium", bestTime: "Nov-Mar, turtle nesting season" },
      { name: "Ashwem Beach", area: "North", desc: "Upscale beach shacks, shallow waters. Great for sunset cocktails and swimming.", lat: 15.6420, lng: 73.7230, tags: ["upscale", "sunset", "swimming"], timeToSpend: "2-4 hours", rating: 4.5, popularity: "low", bestTime: "Nov-Mar, any time" },
      { name: "Arambol Beach", area: "North", desc: "Bohemian vibe, drum circles at sunset, sweet water lake behind the cliff. Goa's hippie capital.", lat: 15.6830, lng: 73.7060, tags: ["bohemian", "drum-circles", "sweet-lake"], timeToSpend: "3-4 hours", rating: 4.0, popularity: "high", bestTime: "Nov-Mar, morning for yoga" },
      { name: "Betalbatim Beach", area: "South", desc: "Quiet, clean, local fishermen. Called 'Sunset Beach' for a reason.", lat: 15.3050, lng: 73.9140, tags: ["quiet", "sunset", "authentic"], timeToSpend: "2-3 hours", rating: 4.2, popularity: "low", bestTime: "Nov-Mar, sunset, night for bioluminescence" },
      { name: "Galgibaga Beach", area: "South", desc: "Pristine, protected turtle nesting site. Almost no tourists. Goa's cleanest beach.", lat: 14.9700, lng: 74.0570, tags: ["pristine", "turtles", "empty"], timeToSpend: "2-3 hours", rating: 4.6, popularity: "low", bestTime: "Nov-Mar, turtle nesting season" },
      { name: "Kakolem Beach (Tiger Beach)", area: "South", desc: "Stunning secluded beach accessible only by steep descent, featuring a hidden waterfall, pristine golden sands, and dramatic cliffs. Complete isolation from tourist crowds.", lat: 15.007, lng: 73.946, tags: ["secluded", "adventure", "waterfall", "hidden"], timeToSpend: "2-3 hours", rating: 4.7, popularity: "low", bestTime: "Nov-Mar, avoid monsoon for safety" },
      { name: "Betul Beach", area: "South", desc: "Tranquil fishing village beach at the delta of Sal River, famous for fresh mussels and seafood. Features a 17th-century fort and authentic coastal village atmosphere.", lat: 15.183, lng: 73.919, tags: ["fishing-village", "seafood", "quiet", "authentic"], timeToSpend: "1-2 hours", rating: 4.3, popularity: "low", bestTime: "Oct-Mar, morning for fishing activity" },
      { name: "Querim Beach (Keri Beach)", area: "North", desc: "Northernmost beach of Goa bordered by Terekhol River and surrounded by casuarina trees. Completely secluded with views of Tiracol Fort across the river.", lat: 15.720, lng: 73.689, tags: ["secluded", "quiet", "northernmost", "fort-views"], timeToSpend: "2-3 hours", rating: 4.4, popularity: "low", bestTime: "Nov-Feb, morning" },
      { name: "Talpona Beach", area: "South", desc: "Pristine golden sand beach where Talpona River meets the Arabian Sea. Long stretch of soft sand with crystal-clear waters and minimal commercialization.", lat: 15.030, lng: 74.014, tags: ["pristine", "quiet", "river-meets-sea", "golden-sand"], timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Oct-Mar, any time" },
      { name: "Velsao Beach", area: "South", desc: "Serene white shell-studded beach lined with coconut trees. Known for its unique white shells, starfish, and calm waters. Popular with locals but undiscovered by tourists.", lat: 15.407, lng: 73.838, tags: ["shells", "quiet", "local-favorite", "calm-waters"], timeToSpend: "1-2 hours", rating: 4.1, popularity: "low", bestTime: "Nov-Mar, morning" },
      { name: "Polem Beach", area: "South", desc: "Southernmost beach at Goa-Karnataka border, frequented by white-bellied eagles and dolphins. Golden sands with rocky outcrops and stunning natural beauty.", lat: 14.956, lng: 74.025, tags: ["southernmost", "dolphins", "wildlife", "remote"], timeToSpend: "2-3 hours", rating: 4.4, popularity: "low", bestTime: "Oct-Mar, early morning for dolphins" },
    ]
  },

  churches: {
    icon: "⛪",
    title: "Churches & Heritage",
    color: "#A855F7",
    items: [
      { name: "Basilica of Bom Jesus", area: "Central", desc: "UNESCO World Heritage. Houses St. Francis Xavier's remains. Baroque masterpiece from 1605.", lat: 15.5008, lng: 73.9114, tags: ["UNESCO", "must-visit", "baroque"], timeToSpend: "45 mins - 1 hour", rating: 4.6, popularity: "high", bestTime: "Morning (9am-12pm), Nov-Feb" },
      { name: "Sé Cathedral", area: "Central", desc: "Largest church in Asia. Portuguese-Manueline style. Famous Golden Bell inside.", lat: 15.5038, lng: 73.9121, tags: ["largest-in-asia", "golden-bell", "UNESCO"], timeToSpend: "20-30 mins", rating: 4.5, popularity: "high", bestTime: "Morning near opening (7:30am), Nov-Mar" },
      { name: "Church of St. Cajetan", area: "Central", desc: "Modeled on St. Peter's Basilica in Rome. Corinthian columns, stunning frescoes.", lat: 15.5045, lng: 73.9108, tags: ["rome-inspired", "frescoes", "baroque"], timeToSpend: "30-45 mins", rating: 4.4, popularity: "medium", bestTime: "Morning (9am-12pm), Nov-Mar" },
      { name: "Church of St. Francis of Assisi", area: "Central", desc: "Houses the Archaeological Museum. Manueline-style doorway, gilded woodwork inside.", lat: 15.5020, lng: 73.9110, tags: ["museum", "manueline", "art"], timeToSpend: "20-30 mins", rating: 4.5, popularity: "medium", bestTime: "Morning, Oct-Feb, includes museum visit" },
      { name: "Chapel of Our Lady of the Mount", area: "Central", desc: "Hilltop chapel with panoramic views of Old Goa. Peaceful, rarely visited.", lat: 15.5055, lng: 73.9095, tags: ["hilltop", "views", "quiet"], timeToSpend: "1 hour", rating: 4.3, popularity: "medium", bestTime: "Sunset for views, Nov-Feb" },
      { name: "Mae de Deus Church, Saligao", area: "North", desc: "Neo-Gothic beauty. Stunning at night when illuminated. Known locally as 'Monte de Saligao'.", lat: 15.5600, lng: 73.7910, tags: ["neo-gothic", "night-visit", "photogenic"], timeToSpend: "30 mins", rating: 4.4, popularity: "low", bestTime: "Evening when illuminated, year-round" },
      { name: "Three Kings Chapel, Cansaulim", area: "South", desc: "Hilltop church from 1599. Famous for ghost legends and panoramic views of the Arabian Sea.", lat: 15.3370, lng: 73.9010, tags: ["legends", "hilltop", "views"], timeToSpend: "1-1.5 hours", rating: 4.3, popularity: "medium", bestTime: "Late afternoon for sunset, Jan 6 for feast" },
      { name: "Church of Our Lady of the Rosary", area: "Central", desc: "One of the oldest churches in Goa (1544). Manueline style. Views over Old Goa.", lat: 15.5060, lng: 73.9100, tags: ["oldest", "manueline", "historic"], timeToSpend: "20 mins", rating: 4.4, popularity: "low", bestTime: "Morning, year-round" },
      { name: "Rachol Seminary", area: "South", desc: "Founded 1560 from Muslim fort remains. One of Asia's oldest seminaries. Rarely visited gem.", lat: 15.3490, lng: 73.9700, tags: ["seminary", "historic", "off-beat"], timeToSpend: "1 hour", rating: 4.2, popularity: "low", bestTime: "Morning (7am-12pm), year-round" },
      { name: "St. Anthony Church, Siolim", area: "North", desc: "Neo-Gothic church (1907) on banks of Chapora River with unique statue of St. Anthony holding a serpent. Peaceful riverside setting surrounded by lush greenery.", lat: 15.6102, lng: 73.7536, tags: ["architecture", "riverside", "peaceful"], timeToSpend: "30-45 mins", rating: 4.5, popularity: "low", bestTime: "Morning, year-round" },
      { name: "Chapel of St. Catherine, Old Goa", area: "Central", desc: "Historic chapel (1510) built by Afonso de Albuquerque to commemorate Portuguese capture of Goa. Part of UNESCO World Heritage Site.", lat: 15.5024, lng: 73.9115, tags: ["heritage", "UNESCO", "historical"], timeToSpend: "15-20 mins", rating: 4.0, popularity: "low", bestTime: "Morning, Nov-Feb" },
      { name: "St. Thomas Church, Aldona", area: "North", desc: "Baroque church (1596) built on high plateau overlooking Mapusa River with stunning river views. Ornate decorations, biblical murals, and grand statues.", lat: 15.5875, lng: 73.8658, tags: ["baroque", "riverside", "murals"], timeToSpend: "30 mins", rating: 4.3, popularity: "low", bestTime: "Morning (8-10am), year-round" },
      { name: "Church of the Holy Spirit, Margao", area: "South", desc: "Magnificent 17th-century church (1675) in Portuguese Baroque style with impressive reredos rising to high ceiling. Well-preserved whitewashed main church.", lat: 15.2741, lng: 73.9580, tags: ["baroque", "architecture", "margao"], timeToSpend: "30 mins", rating: 4.5, popularity: "medium", bestTime: "Morning (9am-12pm), year-round" },
    ]
  },

  forts: {
    icon: "🏰",
    title: "Forts",
    color: "#F59E0B",
    items: [
      { name: "Fort Aguada", area: "North", desc: "Well-preserved 17th-century Portuguese fort with lighthouse. Named for freshwater springs.", lat: 15.4920, lng: 73.7730, tags: ["lighthouse", "well-preserved", "views"], timeToSpend: "1-1.5 hours", rating: 4.3, popularity: "high", bestTime: "Sunset for views, Oct-Mar" },
      { name: "Chapora Fort", area: "North", desc: "The Dil Chahta Hai fort. Best sunset viewpoint. Panoramic views of Vagator and Arabian Sea.", lat: 15.6046, lng: 73.7370, tags: ["sunset", "iconic", "panoramic"], timeToSpend: "1-1.5 hours", rating: 4.5, popularity: "high", bestTime: "Late afternoon before sunset, Nov-Jan" },
      { name: "Cabo de Rama Fort", area: "South", desc: "Named after Lord Rama. Wild, overgrown, dramatic. Chapel inside still active. Sea views.", lat: 15.0900, lng: 73.9300, tags: ["wild", "ancient", "off-beat"], timeToSpend: "1-2 hours", rating: 4.4, popularity: "medium", bestTime: "Evening for sunset over Arabian Sea, Nov-Mar" },
      { name: "Reis Magos Fort", area: "North", desc: "Restored fort with art gallery inside. Views of Mandovi River. Less crowded than Aguada.", lat: 15.4970, lng: 73.8070, tags: ["art-gallery", "restored", "river-views"], timeToSpend: "1-1.5 hours", rating: 4.6, popularity: "medium", bestTime: "Morning for softer light, Oct-Mar" },
      { name: "Corjuem Fort", area: "North", desc: "Tiny island fort on Mapusa River. Atmospheric, almost never visited. Real hidden gem.", lat: 15.5370, lng: 73.8660, tags: ["island", "hidden-gem", "atmospheric"], timeToSpend: "45 mins - 1 hour", rating: 3.9, popularity: "low", bestTime: "Morning or evening, Nov-Mar" },
      { name: "Tiracol Fort", area: "North", desc: "Northernmost point of Goa. Now a heritage hotel. Tiny chapel inside. Border of Maharashtra.", lat: 15.7260, lng: 73.6830, tags: ["northernmost", "heritage-hotel", "remote"], timeToSpend: "1.5-2 hours", rating: 4.0, popularity: "medium", bestTime: "Lunch with views, Oct-Mar" },
      { name: "Mormugao Fort", area: "South", desc: "Early 17th-century Portuguese fort (1624) overlooking Varca Beach and Arabian Sea. Mostly in ruins but bastions remain standing. Features two historic fountains.", lat: 15.4116, lng: 73.7986, tags: ["ruins", "beach-views", "historical"], timeToSpend: "1-1.5 hours", rating: 3.8, popularity: "low", bestTime: "Morning, carry water and food" },
      { name: "Alorna Fort", area: "North", desc: "17th-century fort on banks of Chapora River in Pernem. Protected monument undergoing ASI renovation. Free entry, uncommercialized gem with river views.", lat: 15.7158, lng: 73.8986, tags: ["riverside", "heritage", "off-beaten"], timeToSpend: "1-1.5 hours", rating: 4.1, popularity: "low", bestTime: "Nov-Feb, morning hours" },
      { name: "Rachol Fort", area: "South", desc: "Severely ruined fort on banks of Zuari River. Originally built by Sultanate of Bijapur, later Portuguese. Protected gate with coat of arms still visible.", lat: 15.3622, lng: 73.9436, tags: ["ruins", "heritage", "riverside"], timeToSpend: "30-45 mins", rating: 3.5, popularity: "low", bestTime: "Morning, combine with Rachol Seminary, year-round" },
      { name: "Sinquerim Fort", area: "North", desc: "17th-century fort (1612) constructed as extension of Aguada Fort, overlooking Sinquerim Beach. Lesser-known but historically important. Beautiful Arabian Sea views.", lat: 15.4976, lng: 73.7649, tags: ["beach-views", "portuguese", "hidden-gem"], timeToSpend: "45 mins - 1 hour", rating: 4.2, popularity: "low", bestTime: "Morning or late afternoon, Oct-Mar" },
    ]
  },

  mansions: {
    icon: "🏛️",
    title: "Heritage Mansions",
    color: "#EC4899",
    items: [
      { name: "Menezes Braganza House, Chandor", area: "South", desc: "Biggest Portuguese mansion in Goa. 450+ years, 10,000 sqm. Belgian chandeliers, Ming vases, 5000-book library. Family gives tours. ₹150/wing.", lat: 15.2614, lng: 74.0434, tags: ["must-visit", "450-years", "museum-like"], timeToSpend: "1-2 hours", rating: 4.2, popularity: "medium", bestTime: "Morning, Oct-Mar" },
      { name: "Palácio do Deão, Quepem", area: "South", desc: "18th-century palace on Kushavati River. Hindu-Portuguese fusion. Pre-book lunch — home-cooked Indo-Portuguese food from their garden. Closed Wed.", lat: 15.2136, lng: 74.0736, tags: ["lunch-available", "river-view", "pre-book"], timeToSpend: "2-3 hours", rating: 4.8, popularity: "medium", bestTime: "Morning or late afternoon, book lunch 24hrs ahead" },
      { name: "Fernandes House, Chandor", area: "South", desc: "500+ years old. Hidden underground tunnel to a nearby church. More intimate than Braganza.", lat: 15.2610, lng: 74.0460, tags: ["tunnels", "intimate", "500-years"], timeToSpend: "1 hour", rating: 4.3, popularity: "low", bestTime: "Weekday mornings 10am-5pm" },
      { name: "Figueiredo House, Loutolim", area: "South", desc: "450-year-old mansion. Still inhabited by the family. Indo-Portuguese furniture, grand ballroom.", lat: 15.3090, lng: 73.9680, tags: ["lived-in", "ballroom", "antiques"], timeToSpend: "1-2 hours", rating: 4.5, popularity: "medium", bestTime: "Year-round, book heritage tour ahead" },
      { name: "Casa Araujo Alvares, Loutolim", area: "South", desc: "One of the oldest houses in Goa. Connected to the Ancestral Goa museum. Beautiful gardens.", lat: 15.3100, lng: 73.9670, tags: ["oldest", "museum", "gardens"], timeToSpend: "1 hour", rating: 3.8, popularity: "medium", bestTime: "9am-1pm or 2pm-6pm, tours every 15 mins" },
      { name: "Salvador Costa Mansion", area: "South", desc: "19th-century mansion built by priest brothers, showcasing Baroque and Indian architectural fusion with Gothic windows, elaborate balconies, antique Portuguese furniture and tiles.", lat: 15.3408, lng: 73.9835, tags: ["heritage", "architecture", "baroque", "photo-spot"], timeToSpend: "1 hour", rating: 4.4, popularity: "low", bestTime: "Oct-Mar, mornings" },
      { name: "Bragança Pereira Mansion", area: "South", desc: "17th-century twin mansion near Chandor church, one of Goa's largest colonial residences with 24 sash windows, filled with 400-year-old antiques and art.", lat: 15.2617, lng: 74.0433, tags: ["heritage", "museum", "antiques", "colonial"], timeToSpend: "1.5-2 hours", rating: 4.5, popularity: "low", bestTime: "Morning guided tours, Oct-Mar" },
      { name: "Mansão Curtorim", area: "South", desc: "236-year-old Indo-Portuguese mansion meticulously restored by CGH Earth, facing tranquil Communidade Lake, surrounded by giant trees and birdsong.", lat: 15.2833, lng: 73.9667, tags: ["heritage", "boutique-stay", "lake-view", "restored"], timeToSpend: "2-3 hours", rating: 4.7, popularity: "low", bestTime: "Year-round, especially Oct-Feb" },
      { name: "Casa da Moeda (Mint House)", area: "Central", desc: "Historic Portuguese mint house from 1834-1841 in Panjim's Post Office Square. Goa's only surviving colonial mint building, now private residence.", lat: 15.4909, lng: 73.8278, tags: ["heritage", "history", "colonial", "architecture"], timeToSpend: "30 mins", rating: 4.0, popularity: "low", bestTime: "View from outside only, mornings" },
      { name: "Silva Heritage Mansion", area: "South", desc: "350-year-old Indo-Portuguese mansion in quiet Benaulim village, restored as heritage hotel and event venue, showcasing confluence of Portuguese and Hindu architectural styles.", lat: 15.2547, lng: 73.9356, tags: ["heritage", "boutique-stay", "restored", "events"], timeToSpend: "1-2 hours", rating: 4.6, popularity: "low", bestTime: "Oct-Mar, can book heritage lunch" },
    ]
  },

  islands: {
    icon: "🏝️",
    title: "Islands",
    color: "#14B8A6",
    items: [
      { name: "Divar Island", area: "Central", desc: "Not connected by road — free ferry from Ribandar. Frozen in time: Baroque churches, paddy fields, oyster-shell windows. Book guided tour with Make It Happen or Soul Travelling.", lat: 15.5120, lng: 73.8870, tags: ["ferry", "time-capsule", "guided-tours"], timeToSpend: "Half day (5-6 hours)", rating: 4.0, popularity: "medium", bestTime: "Oct-Mar, take bike to explore" },
      { name: "Chorao Island", area: "Central", desc: "Dr. Salim Ali Bird Sanctuary. Mangrove kayaking. Portuguese-era chapel hike. Mud-bathing in lake.", lat: 15.5250, lng: 73.8780, tags: ["birds", "mangroves", "kayaking"], timeToSpend: "2-3 hours", rating: 4.4, popularity: "medium", bestTime: "Oct-Mar (migratory birds), early morning" },
      { name: "St. George Island (Ilha de São Jorge)", area: "Central", desc: "Tiny island in Mandovi River. Old Portuguese chapel ruins. Almost no tourists visit.", lat: 15.5050, lng: 73.8600, tags: ["ruins", "secluded", "river"], timeToSpend: "1-2 hours", rating: 3.8, popularity: "low", bestTime: "Oct-Mar, morning or evening" },
      { name: "Grande Island", area: "South", desc: "Main snorkeling and diving destination. Boat trips from Vasco. Monkey Beach, Suzy's Wreck dive site.", lat: 15.3740, lng: 73.8470, tags: ["snorkeling", "diving", "boat-trip"], timeToSpend: "Half day (4-5 hours)", rating: 4.2, popularity: "high", bestTime: "Oct-May, morning dives" },
      { name: "Bat Island", area: "South", desc: "Best diving in Goa. Coral reefs, rays, turtles. Only accessible by dive boat.", lat: 15.3650, lng: 73.8350, tags: ["diving", "coral", "advanced"], timeToSpend: "3-4 hours", rating: 4.3, popularity: "medium", bestTime: "Oct-Dec (best visibility)" },
      { name: "Vanxim Island", area: "Central", desc: "Tiny peaceful islet near Divar accessible by 12-min ferry, no shops or restaurants. Church of Santo Cristo (1879), perfect for kayaking, cycling, and authentic village life.", lat: 15.5459, lng: 73.9118, tags: ["offbeat", "peaceful", "kayaking", "cycling", "village-life"], timeToSpend: "Half day", rating: 4.5, popularity: "low", bestTime: "Oct-Mar, morning ferry from Divar" },
      { name: "Corjuem Island", area: "Central", desc: "River island with 1705 laterite fort across suspension bridge from Aldona. Covered in lush greenery during monsoon, boat rides on Chapora River through mangroves.", lat: 15.5968, lng: 73.8931, tags: ["fort", "suspension-bridge", "offbeat", "kayaking", "mangroves"], timeToSpend: "2-3 hours", rating: 4.1, popularity: "low", bestTime: "Monsoon for greenery, cooler hours" },
      { name: "São Jacinto Island", area: "South", desc: "Small inhabited island in Mormugao Bay connected by causeway. Home to São Jacinto Church, plate coral visible beneath water, kayaking hub on Zuari River.", lat: 15.4167, lng: 73.8500, tags: ["residential", "church", "kayaking", "offbeat", "coral"], timeToSpend: "2-3 hours", rating: 4.2, popularity: "low", bestTime: "Year-round, evening kayaking tours" },
      { name: "Cumbarjua Canal", area: "Central", desc: "Hidden 15km brackish waterway linking Zuari and Mandovi rivers. Mangrove-lined canals hosting wild mugger crocodiles, boat safaris, birdwatching with Brahminy kites and kingfishers.", lat: 15.5167, lng: 73.9000, tags: ["crocodiles", "safari", "mangroves", "birdwatching", "offbeat"], timeToSpend: "2-3 hours", rating: 4.6, popularity: "low", bestTime: "Nov-Feb, early morning 7-9am for crocodiles" },
    ]
  },

  localSpots: {
    icon: "📍",
    title: "Local Spots & Villages",
    color: "#6366F1",
    items: [
      { name: "Fontainhas Latin Quarter, Panjim", area: "Central", desc: "Goa's Portuguese quarter. Pastel houses, azulejo tiles, oyster-shell windows. Walk early morning for fewer tourists.", lat: 15.4956, lng: 73.8315, tags: ["portuguese", "photography", "heritage-walk"], timeToSpend: "2-3 hours", rating: 4.5, popularity: "high", bestTime: "Early morning or evening, Oct-Mar" },
      { name: "Assagao Village", area: "North", desc: "Goa's hippest village. Art cafes, yoga studios, boutique shops in Portuguese houses. Local expat hub.", lat: 15.5870, lng: 73.7740, tags: ["cafes", "yoga", "trendy"], timeToSpend: "Half day", rating: 4.4, popularity: "high", bestTime: "Year-round, avoid peak summer" },
      { name: "Chandor Village", area: "South", desc: "Ancient Kadamba dynasty capital. Grand Portuguese mansions, quiet village square, rich history.", lat: 15.2610, lng: 74.0430, tags: ["historic", "mansions", "off-beat"], timeToSpend: "2-3 hours", rating: 4.3, popularity: "medium", bestTime: "Morning, Oct-Mar" },
      { name: "Saligao Village", area: "North", desc: "Heritage homes, laterite roads, the stunning Mae de Deus church. Real village Goa.", lat: 15.5590, lng: 73.7920, tags: ["village-life", "church", "heritage"], timeToSpend: "1-2 hours", rating: 4.2, popularity: "medium", bestTime: "Morning for church visit, year-round" },
      { name: "Aldona Village", area: "North", desc: "Corjuem Fort nearby. Beautiful Mapusa River crossing. Old Portuguese houses, toddy tappers.", lat: 15.5410, lng: 73.8710, tags: ["toddy", "river", "authentic"], timeToSpend: "2-3 hours", rating: 4.3, popularity: "medium", bestTime: "Morning, Oct-Mar for Corjuem Fort" },
      { name: "Ponda (Temple Belt)", area: "Central", desc: "Goa's Hindu heartland. Shri Manguesh, Shri Mahalsa, Shri Shantadurga temples. Spice plantations nearby.", lat: 15.4000, lng: 74.0100, tags: ["temples", "hindu-heritage", "spices"], timeToSpend: "Half day", rating: 4.4, popularity: "high", bestTime: "Morning, year-round" },
      { name: "Mario Gallery, Porvorim", area: "North", desc: "Museum dedicated to legendary Goan cartoonist Mario Miranda. His art defines Goan identity.", lat: 15.5220, lng: 73.8190, tags: ["art", "cartoons", "goan-culture"], timeToSpend: "30-45 mins", rating: 4.5, popularity: "medium", bestTime: "Mon-Sat, 9am-5pm" },
      { name: "Netravali Bubble Lake & Wildlife Sanctuary", area: "South", desc: "Goa's largest wildlife sanctuary (211 sq km) in Western Ghats. Mysterious Budbudyanchi Tali lake with bubbles that respond to clapping, waterfalls, dense forests.", lat: 15.2203, lng: 74.1369, tags: ["nature", "wildlife", "offbeat", "trekking", "waterfall"], timeToSpend: "Half day", rating: 4.5, popularity: "low", bestTime: "Morning 8:30am-4:30pm, Oct-Mar" },
      { name: "Tambdi Surla Temple", area: "East", desc: "Goa's oldest and only surviving 12th century temple, built entirely of black basalt stone in Kadamba architectural style. Deep in Bhagwan Mahaveer Sanctuary.", lat: 15.4389, lng: 74.2522, tags: ["temple", "heritage", "ancient", "architecture", "offbeat"], timeToSpend: "1-2 hours", rating: 4.6, popularity: "medium", bestTime: "Morning, Oct-Mar, combines with Dudhsagar" },
      { name: "Carambolim Lake Bird Sanctuary", area: "Central", desc: "Man-made lake 2km from Old Goa, haven for 126 resident and 107 migratory bird species including Greater Flamingo and Great White Pelican.", lat: 15.4986, lng: 73.8742, tags: ["birdwatching", "nature", "lake", "wildlife", "photography"], timeToSpend: "2-3 hours", rating: 4.4, popularity: "low", bestTime: "Early morning, Nov-Mar for migratory birds" },
      { name: "Kala Academy Cultural Centre", area: "Central", desc: "Goa's premier cultural institution at Campal Panjim. 5 state-of-the-art venues, art gallery, exhibition halls. Hosts theatre, music, dance performances.", lat: 15.4942, lng: 73.8178, tags: ["culture", "art", "music", "theatre", "architecture"], timeToSpend: "1-2 hours", rating: 4.5, popularity: "medium", bestTime: "Check performance schedule, evenings best" },
    ]
  },

  food: {
    icon: "🍽️",
    title: "Must-Try Dishes",
    color: "#EF4444",
    items: [
      { name: "Fish Curry Rice (Xit Koddi)", desc: "THE staple of Goa. Coconut-based curry with fresh local fish, served with rice. Every household has their own recipe.", tags: ["staple", "coconut", "daily-meal"], where: "Kokni Kanteen, Ritz Classic, any local home", timeToSpend: "30-45 mins", rating: 4.8, popularity: "high", bestTime: "Lunch" },
      { name: "Pork Vindaloo", desc: "From Portuguese 'vinha d'alhos'. Fiery red curry with vinegar, garlic, local spices. Not the British version you know.", tags: ["portuguese-origin", "spicy", "pork"], where: "Viva Panjim, Bhatti Village", timeToSpend: "45 mins - 1 hour", rating: 4.7, popularity: "high", bestTime: "Lunch or Dinner" },
      { name: "Chicken Cafreal", desc: "Green masala marinated, pan-fried chicken. African-Portuguese origin via Mozambique. Smoky, herby, incredible.", tags: ["green-masala", "african-origin", "smoky"], where: "Bhatti Village, Kokni Kanteen", timeToSpend: "30-45 mins", rating: 4.8, popularity: "high", bestTime: "Lunch or Dinner" },
      { name: "Pomfret Recheado", desc: "Whole fish stuffed with spicy red masala, shallow fried till crispy. 'Rechear' means 'to stuff' in Portuguese.", tags: ["stuffed-fish", "crispy", "signature"], where: "Viva Panjim, Ritz Classic", timeToSpend: "45 mins - 1 hour", rating: 4.6, popularity: "medium", bestTime: "Lunch or Dinner" },
      { name: "Crab Xec Xec", desc: "Crab in thick coconut gravy with cinnamon, pepper, cumin. No English translation for 'xec xec'. Rich and aromatic.", tags: ["crab", "coconut", "aromatic"], where: "Ritz Classic, Martin's Corner", timeToSpend: "45 mins - 1 hour", rating: 4.5, popularity: "medium", bestTime: "Lunch or Dinner" },
      { name: "Prawn Balchão", desc: "Fiery pickle-curry from Macao via Portuguese. Prawns in chili-garlic masala. Gets better the next day.", tags: ["pickle-curry", "macao-origin", "spicy"], where: "Ritz Classic, Kokni Kanteen", timeToSpend: "30-45 mins", rating: 4.7, popularity: "high", bestTime: "Lunch or Dinner" },
      { name: "Chicken/Mutton Xacuti", desc: "Complex curry with 15+ toasted spices, poppy seeds, coconut. Sunday-special dish. Rich and layered.", tags: ["15-spices", "complex", "sunday-dish"], where: "Kokni Kanteen, Nostalgia", timeToSpend: "45 mins - 1 hour", rating: 4.6, popularity: "medium", bestTime: "Lunch or Dinner" },
      { name: "Sorpotel", desc: "Portuguese-origin pork offal stew. Pickled with vinegar, intensely spiced. Festival dish. An acquired taste.", tags: ["offal", "festival", "intense"], where: "Local homes, Bhatti Village", timeToSpend: "45 mins - 1 hour", rating: 4.4, popularity: "low", bestTime: "Lunch" },
      { name: "Ros Omelette", desc: "Goa street food legend. Spiced omelette smothered in thick red/green gravy (ros). Found at roadside stalls.", tags: ["street-food", "unique", "late-night"], where: "Street stalls in Panjim, Mapusa", timeToSpend: "15-20 mins", rating: 4.6, popularity: "high", bestTime: "Breakfast or Evening" },
      { name: "Choris Pao", desc: "Goan pork sausage in a bread roll. Spicy, tangy, perfect snack. Buy raw sausage strings at Mapusa Market.", tags: ["sausage", "street-food", "pork"], where: "Mapusa Market, local bakeries", timeToSpend: "10-15 mins", rating: 4.7, popularity: "high", bestTime: "Breakfast or Anytime" },
      { name: "Bebinca", desc: "The queen of Goan desserts. 7-16 layers of coconut, eggs, ghee, individually baked. Takes hours to make.", tags: ["layered", "iconic", "coconut"], where: "Any good Goan restaurant, local bakeries", timeToSpend: "20-30 mins", rating: 4.5, popularity: "medium", bestTime: "Dessert (Anytime)" },
      { name: "Serradura", desc: "Portuguese 'sawdust pudding'. Crushed Marie biscuits layered with sweetened cream. Simple, addictive.", tags: ["portuguese", "simple", "cream"], where: "Viva Panjim, Cafe Bodega", timeToSpend: "15-20 mins", rating: 4.3, popularity: "medium", bestTime: "Dessert (Anytime)" },
      { name: "Dodol", desc: "Sticky, dark, jaggery-coconut sweet. Slow-cooked for hours. Christmas specialty but available year-round.", tags: ["jaggery", "christmas", "slow-cooked"], where: "Local bakeries, Mapusa Market", timeToSpend: "10-15 mins", rating: 4.2, popularity: "low", bestTime: "Dessert (Anytime)" },
      { name: "Poi / Pao", desc: "Local Goan bread. Poder (baker) delivers door-to-door at dawn. Poi is round, Pao is the classic roll.", tags: ["bread", "daily", "baker-delivery"], where: "Any local bakery, early morning", timeToSpend: "5-10 mins", rating: 4.4, popularity: "high", bestTime: "Breakfast or with meals" },
      { name: "Sol Kadhi", desc: "Pink coconut milk + kokum digestive drink. Cooling, tangy. Always have it after a spicy fish meal.", tags: ["digestive", "pink", "kokum"], where: "Served with thalis everywhere", timeToSpend: "5-10 mins", rating: 4.6, popularity: "medium", bestTime: "After meals" },
      { name: "Sanna (Goan Rice Cakes)", desc: "Soft, fluffy steamed rice cakes made from fermented rice batter with coconut milk. Like idlis but sweeter. Traditional side dish to spicy gravies.", tags: ["vegetarian", "breakfast", "traditional", "coconut"], where: "Breakfast shacks in South Goa, Nostalgia (Raia), family-run restaurants", timeToSpend: "20-30 mins", rating: 4.5, popularity: "low", bestTime: "Breakfast or Lunch" },
      { name: "Tisreo (Goan Clam Fry)", desc: "Dry coconut-based preparation of clams. Small clams sautéed with grated coconut, spices, and green chilies. A beloved side dish locals order by default.", tags: ["seafood", "spicy", "coconut", "side-dish"], where: "Kokni Kanteen (Panjim), Ritz Classic, local fish thali restaurants", timeToSpend: "20-30 mins", rating: 4.4, popularity: "low", bestTime: "Lunch" },
      { name: "Kismur (Dry Fish Salad)", desc: "Traditional Goan dry fish salad made with salted sun-dried shrimp mixed with grated coconut, onions, and spices. A tangy, salty condiment. Deeply authentic.", tags: ["seafood", "traditional", "side-dish", "preserved"], where: "Local tavernas in Quepem, Cuncolim, Nostalgia (Raia)", timeToSpend: "10-15 mins", rating: 4.2, popularity: "low", bestTime: "Lunch or Dinner" },
      { name: "Ambot Tik (Sour-Spicy Fish Curry)", desc: "Hot and tangy shark or fish curry. Unlike most Goan curries, uses NO coconut — relies on red chilies, tamarind, and kokum for sour-hot punch.", tags: ["seafood", "spicy", "sour", "no-coconut"], where: "Viva Panjim, Martin's Corner, traditional Catholic Goan restaurants", timeToSpend: "30-45 mins", rating: 4.6, popularity: "medium", bestTime: "Lunch" },
      { name: "Bhaji Pao", desc: "Spiced mixed vegetable curry served with fresh bread rolls. The ultimate Goan vegetarian street food, perfect for breakfast or evening snack.", tags: ["vegetarian", "street-food", "breakfast", "budget-friendly"], where: "Street stalls in Mapusa, Margao, Panjim municipal garden", timeToSpend: "15-20 mins", rating: 4.5, popularity: "medium", bestTime: "Breakfast or Evening" },
    ]
  },

  restaurants: {
    icon: "🍴",
    title: "Restaurants",
    color: "#F97316",
    items: [
      { name: "Kokni Kanteen", area: "Central", desc: "Panjim institution since 1972. THE fish thali in Goa. Expect 30-60 min wait at lunch. Worth every minute.", lat: 15.4967, lng: 73.8269, tags: ["thali", "institution", "must-visit"], price: "₹₹", timeToSpend: "1-1.5 hours", rating: 4.5, popularity: "high", bestTime: "Lunch" },
      { name: "Viva Panjim", area: "Central", desc: "Inside a 150-year-old Portuguese house in Fontainhas. Pork Vindaloo, Recheado, Serradura. Atmospheric.", lat: 15.4965, lng: 73.8312, tags: ["portuguese-house", "heritage", "romantic"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.6, popularity: "high", bestTime: "Dinner" },
      { name: "Bhatti Village, Nerul", area: "North", desc: "Family home turned restaurant. Hidden in a village lane. Homemade feni, ox tongue, clams. Where Goans eat.", lat: 15.5153, lng: 73.7872, tags: ["hidden-gem", "authentic", "ox-tongue"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.7, popularity: "medium", bestTime: "Lunch or Dinner" },
      { name: "Ritz Classic, Panjim", area: "Central", desc: "Legendary for seafood thalis. Chonak fish, Crab Masala, Prawn Balchão. Lunch is the move.", lat: 15.4986, lng: 73.8266, tags: ["seafood", "thali", "legendary"], price: "₹₹", timeToSpend: "1-1.5 hours", rating: 4.5, popularity: "high", bestTime: "Lunch or Dinner" },
      { name: "Bombil, Panjim", area: "Central", desc: "Set in a Goan-Portuguese bungalow. Named after bombil fish (Bombay duck). Melt-in-mouth rawa fry.", lat: 15.4936, lng: 73.8267, tags: ["bungalow", "rawa-fry", "homely"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.6, popularity: "high", bestTime: "Dinner" },
      { name: "Martin's Corner, Betalbatim", area: "South", desc: "20+ year institution. Live music some nights. Famous Crab Xec Xec and Prawn Curry.", lat: 15.3040, lng: 73.9190, tags: ["institution", "live-music", "seafood"], price: "₹₹₹", timeToSpend: "1.5-2 hours", rating: 4.6, popularity: "high", bestTime: "Lunch or Dinner" },
      { name: "Vinayak Family Restaurant, Assagao", area: "North", desc: "Tiny, no-frills. Massive thalis at absurd prices. Where local construction workers eat. Incredibly authentic.", lat: 15.5880, lng: 73.7770, tags: ["budget", "thali", "local-secret"], price: "₹", timeToSpend: "45 mins - 1 hour", rating: 4.4, popularity: "medium", bestTime: "Lunch" },
      { name: "Souza Lobo, Calangute", area: "North", desc: "Beachfront since 1932. Tandoor Kingfish, Crab Rechado, Grilled Lobster. Touristy but earned its reputation.", lat: 15.5430, lng: 73.7550, tags: ["beachfront", "since-1932", "iconic"], price: "₹₹₹", timeToSpend: "1.5-2 hours", rating: 4.5, popularity: "high", bestTime: "Lunch" },
      { name: "Nostalgia, Raia", area: "South", desc: "Late Chef Fernando's legacy. Old Portuguese house. Massive veg/non-veg Goan selection. Ancient recipes revived.", lat: 15.3400, lng: 73.9600, tags: ["chef-legacy", "ancient-recipes", "portuguese-house"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.7, popularity: "low", bestTime: "Lunch or Dinner" },
      { name: "Cafe Bodega (Sunaparanta)", area: "Central", desc: "Art gallery + cafe in a gorgeous Portuguese mansion. Great coffee, carrot cake. Browse contemporary art exhibits.", lat: 15.4939, lng: 73.8276, tags: ["art-gallery", "cafe", "portuguese-mansion"], price: "₹₹", timeToSpend: "1-1.5 hours", rating: 4.4, popularity: "medium", bestTime: "Breakfast or Lunch" },
      { name: "Gunpowder, Assagao", area: "North", desc: "South Indian-meets-Goan in a beautiful garden setting. Appams, Malabar curry, Goan fish. Popular with expats.", lat: 15.5880, lng: 73.7730, tags: ["south-indian", "garden", "fusion"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.7, popularity: "high", bestTime: "Lunch or Dinner" },
      { name: "Anand Ashram, Old Goa", area: "Central", desc: "Family-run since decades. Traditional Goan veg thali. On the road to Old Goa churches.", lat: 15.4990, lng: 73.8900, tags: ["vegetarian", "thali", "traditional"], price: "₹", timeToSpend: "45 mins - 1 hour", rating: 4.3, popularity: "low", bestTime: "Lunch" },
      { name: "Fishka Bar & Restaurant", area: "South", desc: "Modest-looking local joint in Betalbatim serving exceptional seafood at very reasonable prices. A true hidden gem where locals outnumber tourists.", lat: 15.2989, lng: 73.9188, tags: ["seafood", "local-favorite", "budget-friendly", "authentic"], price: "₹₹", timeToSpend: "1-1.5 hours", rating: 4.2, popularity: "low", bestTime: "Lunch or Dinner" },
      { name: "The Goan Kitchen", area: "South", desc: "Located in historic Loutolim village, dedicated to preserving traditional Catholic Goan foods with authentic recipes passed down through generations.", lat: 15.3142, lng: 73.9586, tags: ["traditional", "authentic", "heritage-cuisine", "revival"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.6, popularity: "low", bestTime: "Lunch" },
      { name: "Joet's Bar & Restaurant", area: "South", desc: "Local favorite on Bogmalo Beach in Vasco da Gama with stunning sea views. Known for prawn balchao, grilled fish, and butter garlic crab.", lat: 15.3798, lng: 73.8321, tags: ["seafood", "beach-view", "local-favorite", "relaxed"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.4, popularity: "medium", bestTime: "Lunch or Evening" },
      { name: "Longuinhos, Margao", area: "South", desc: "One of the oldest and most iconic eateries in Margao. Family-run since generations. Famous for beef chilli fry, pork sorpotel, and traditional Goan sweets.", lat: 15.2708, lng: 73.9587, tags: ["traditional", "local-favorite", "budget-friendly", "heritage"], price: "₹", timeToSpend: "1-1.5 hours", rating: 4.5, popularity: "medium", bestTime: "Lunch" },
      { name: "Bawri", area: "North", desc: "Contemporary Goan restaurant in Assagao with excellent breakfast menu — a rarity in Goa. Appam and stew, podi idli, keema ghotala. Lovely garden seating.", lat: 15.6012, lng: 73.7589, tags: ["breakfast", "contemporary", "garden-seating", "modern"], price: "₹₹₹", timeToSpend: "1-1.5 hours", rating: 4.5, popularity: "medium", bestTime: "Breakfast or Lunch" },
    ]
  },

  bars: {
    icon: "🍻",
    title: "Bars & Tavernas",
    color: "#8B5CF6",
    items: [
      { name: "Joseph Bar, Fontainhas", area: "Central", desc: "One of Goa's oldest tavernas. 10-15 seats. Beef samosas, kokum feni cocktails. ₹400 cover. Local institution.", lat: 15.4984, lng: 73.8317, tags: ["oldest", "tiny", "feni-cocktails"], price: "₹₹", timeToSpend: "1-2 hours", rating: 4.2, popularity: "medium", bestTime: "Evening, 6-10pm" },
      { name: "Venite, Panjim", area: "Central", desc: "Balcony seating overlooking the street. Colonial charm. Good Goan food + drinks. Vintage feel.", lat: 15.4975, lng: 73.8300, tags: ["balcony", "colonial", "vintage"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.4, popularity: "high", bestTime: "Lunch or early evening" },
      { name: "Taverna, Saligao", area: "North", desc: "Local's bar with zero pretense. Cheap feni, beer, and great conversation. Real susegad vibe.", lat: 15.5590, lng: 73.7910, tags: ["local", "cheap", "authentic"], price: "₹", timeToSpend: "1-2 hours", rating: 4.0, popularity: "low", bestTime: "Evening, after 5pm" },
      { name: "Mafia Cocktail, Panjim", area: "Central", desc: "Cheap flowing urrak and feni. Home-style Goan food. Local hangout where everyone knows everyone.", lat: 15.4960, lng: 73.8250, tags: ["cheap-drinks", "home-style", "local"], price: "₹", timeToSpend: "1-2 hours", rating: 4.3, popularity: "medium", bestTime: "Lunch or early dinner" },
      { name: "Cape Town Cafe, Anjuna", area: "North", desc: "Rooftop bar with great views. Good cocktails, live music some nights. Chill vibe without the club energy.", lat: 15.5730, lng: 73.7380, tags: ["rooftop", "live-music", "cocktails"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.1, popularity: "high", bestTime: "Evening, 6pm-4am" },
      { name: "Sakana, Assagao", area: "North", desc: "Japanese-inspired bar in Assagao. Sake cocktails, sashimi. Different from everything else in Goa.", lat: 15.5880, lng: 73.7740, tags: ["japanese", "cocktails", "unique"], price: "₹₹₹", timeToSpend: "2-3 hours", rating: 4.2, popularity: "medium", bestTime: "Dinner, evening" },
      { name: "Loulou Speakeasy", area: "North", desc: "Hidden 18-seat speakeasy above Assa House accessed through a secret passage. 110-year-old piano, plush velvets, Parisian ambiance. Intimate cocktail experience.", lat: 15.5878, lng: 73.7603, tags: ["speakeasy", "cocktails", "jazz", "piano-bar", "hidden-gem"], price: "₹₹₹", timeToSpend: "2-3 hours", rating: 4.6, popularity: "low", bestTime: "After 7pm, jazz nights" },
      { name: "MTW Bar & Toasties", area: "Central", desc: "Nao Spirits office by day transforms into bar at dusk. Ring the bell at a nondescript door in Panjim. Gin lover's sanctuary with craft cocktails.", lat: 15.4909, lng: 73.8278, tags: ["gin", "craft-cocktails", "hidden-gem", "office-bar"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Evening, 7pm-1am Mon-Sat" },
      { name: "Escobar (Pablos)", area: "North", desc: "Hipster hangout in Assagao. Feni cocktails, artisan gins, craft beers. Themed nights: jazz, blues, retro, piano. Carrom games and laid-back vibes.", lat: 15.5918, lng: 73.7615, tags: ["feni", "craft-beer", "artisan-gin", "local-hangout"], price: "₹₹", timeToSpend: "2-4 hours", rating: 4.4, popularity: "medium", bestTime: "Evening onwards, themed nights" },
      { name: "Antonio@31", area: "Central", desc: "Portuguese heritage tapas bar on Rua 31 de Janeiro in Panjim. Modern mixology with local spirits, small plates, Goan tapas in heritage building.", lat: 15.4967, lng: 73.8265, tags: ["tapas", "portuguese-heritage", "cocktails", "local-spirits"], price: "₹₹₹", timeToSpend: "2-3 hours", rating: 4.5, popularity: "medium", bestTime: "Evening, dinner time" },
      { name: "The Rice Mill", area: "North", desc: "Former rice mill in Morjim repurposed into cafe by day, chic jazz bar at night. Saturday jazz nights, feni old fashioned and dill martini.", lat: 15.6328, lng: 73.7345, tags: ["jazz", "live-music", "feni-cocktails", "heritage"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.3, popularity: "medium", bestTime: "Saturday evenings for jazz, after 6pm" },
      { name: "Calhiz Bar", area: "North", desc: "Village bar in Morjim. 'A village bar where life takes a pause.' Sunset cocktails and local bites in traditional setting.", lat: 15.6315, lng: 73.7352, tags: ["village-bar", "sunset", "local-vibe", "authentic"], price: "₹", timeToSpend: "1-2 hours", rating: 4.2, popularity: "low", bestTime: "Sunset, around 5:30pm onwards" },
    ]
  },

  clubs: {
    icon: "🎵",
    title: "Clubs & Nightlife",
    color: "#D946EF",
    items: [
      { name: "Curlies Beach Shack, Anjuna", area: "North", desc: "Legendary trance/EDM spot right on Anjuna beach. Goes late into the night. Goa party history.", lat: 15.5700, lng: 73.7400, tags: ["trance", "beachfront", "legendary"], price: "₹₹", timeToSpend: "3-5 hours", rating: 4.2, popularity: "high", bestTime: "After 11pm, Mon/Thu parties" },
      { name: "Club LPK (Love Passion Karma)", area: "North", desc: "Built into a hillside with carved stone. Dramatic venue. Pool parties, international DJs.", lat: 15.5530, lng: 73.7580, tags: ["dramatic-venue", "pool-party", "DJs"], price: "₹₹₹", timeToSpend: "3-4 hours", rating: 3.8, popularity: "high", bestTime: "After 10pm, weekends" },
      { name: "Hilltop, Vagator", area: "North", desc: "Open-air hilltop venue. Goa's premier psychedelic trance spot. Sunrise sessions. Legendary.", lat: 15.6000, lng: 73.7350, tags: ["open-air", "psytrance", "sunrise"], price: "₹₹", timeToSpend: "4-6 hours", rating: 4.0, popularity: "high", bestTime: "After 11pm, festival weekends" },
      { name: "Chronicle, Vagator", area: "North", desc: "Newer upscale club. Good sound system, international acts. More polished than the old-school spots.", lat: 15.5970, lng: 73.7380, tags: ["upscale", "sound-system", "modern"], price: "₹₹₹", timeToSpend: "3-4 hours", rating: 4.2, popularity: "high", bestTime: "Sunset to late night" },
      { name: "Shiva Valley, Anjuna", area: "North", desc: "Tuesday night trance parties on Anjuna beach. Open-air, bonfire vibes. Goa's original party scene.", lat: 15.5710, lng: 73.7390, tags: ["tuesday-nights", "bonfire", "trance"], price: "₹₹", timeToSpend: "5-8 hours", rating: 4.0, popularity: "high", bestTime: "Tuesday nights, after 8:30pm" },
      { name: "Silent Noise Club, Palolem", area: "South", desc: "Silent disco on the beach. Everyone gets headphones, pick your channel. Unique South Goa party.", lat: 15.0100, lng: 74.0240, tags: ["silent-disco", "beach", "unique"], price: "₹₹", timeToSpend: "3-5 hours", rating: 3.9, popularity: "medium", bestTime: "Saturday nights, 9pm-4am" },
      { name: "Café Mambo, Baga", area: "North", desc: "Bollywood nights, commercial music. The mainstream Goa party experience. Gets packed.", lat: 15.5560, lng: 73.7510, tags: ["bollywood", "mainstream", "packed"], price: "₹₹", timeToSpend: "3-4 hours", rating: 4.1, popularity: "high", bestTime: "After 10pm, Wednesday ladies night" },
      { name: "Rockwaters (Vortex Parties)", area: "North", desc: "Legendary Saturday techno parties at beachside bar on Morjim beach. Vortex crew's minimal, groovy techno. Nov-May. Intimate beach setting with excellent sound.", lat: 15.6325, lng: 73.7340, tags: ["techno", "minimal", "beach-club", "Saturday-parties"], price: "₹₹", timeToSpend: "4-8 hours", rating: 4.4, popularity: "high", bestTime: "Saturday nights, midnight-6am" },
      { name: "Katzensuppe (Ø phase)", area: "North", desc: "Techno hub for underground music lovers in Morjim. Deep beats, minimalistic setup that enhances music experience. Midnight-6am.", lat: 15.6305, lng: 73.7298, tags: ["techno", "underground", "tech-house", "late-night"], price: "₹₹", timeToSpend: "4-6 hours", rating: 4.3, popularity: "medium", bestTime: "Midnight-6am, peak season" },
      { name: "Twice in Nature", area: "North", desc: "Cultural hub in Arambol. Bar, restaurant and performance space set in the jungle with outdoor stages. Live music, bands, DJs and performances nightly.", lat: 15.6898, lng: 73.7035, tags: ["live-music", "cultural-events", "jungle-setting", "performances"], price: "₹₹", timeToSpend: "3-5 hours", rating: 4.1, popularity: "medium", bestTime: "Nightly events, after 8pm" },
      { name: "Neptune Point (SEMS)", area: "South", desc: "Beach club on Palolem Beach with bonfires, live music, dancing under stars. Accessible by inflatable boats during high tide.", lat: 15.0096, lng: 74.0233, tags: ["beach-club", "bonfires", "live-music", "sunset"], price: "₹₹", timeToSpend: "3-5 hours", rating: 4.2, popularity: "high", bestTime: "Sunset onwards, weekends" },
    ]
  },

  experiences: {
    icon: "✨",
    title: "Feni, Wine & Experiences",
    color: "#10B981",
    items: [
      { name: "Cazulo Floating Feni Experience", area: "South", desc: "Feet in a natural spring, tasting cashew/coconut/dukshiri feni with food pairings. Farm tour, live music. ₹2000-2500/person. Pre-book on Urbanaut app or call +918605008185.", lat: 15.3668, lng: 73.8995, tags: ["must-do", "pre-book", "unique-in-india"], price: "₹₹₹", timeToSpend: "3-4 hours", rating: 4.8, popularity: "medium", bestTime: "Oct-Mar, evening (6:30 PM start)" },
      { name: "Paul John Whisky Distillery", area: "South", desc: "India's first internationally acclaimed single malt. Full distillery tour + tasting. Combine with Cazulo same day.", lat: 15.3610, lng: 73.9370, tags: ["whisky", "distillery-tour", "award-winning"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.7, popularity: "high", bestTime: "11 AM-4 PM, Oct-May" },
      { name: "Sahakari Spice Farm, Ponda", area: "Central", desc: "Walk through cardamom, pepper, cinnamon, vanilla plantations. Includes traditional Goan lunch + feni tasting.", lat: 15.4100, lng: 74.0300, tags: ["spices", "lunch-included", "nature"], price: "₹₹", timeToSpend: "2-3 hours", rating: 3.9, popularity: "high", bestTime: "Morning, Oct-Mar" },
      { name: "Tropical Spice Plantation", area: "Central", desc: "Elephant encounter (ethical bathing), spice walk, buffet lunch. More touristy but well-organized.", lat: 15.3800, lng: 74.0400, tags: ["elephants", "spices", "buffet"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.0, popularity: "high", bestTime: "Morning, Oct-Mar" },
      { name: "Fontainhas Heritage Walk", area: "Central", desc: "Guided walk through Latin Quarter. Food tastings, stories of Portuguese era. Book via Make It Happen or Soul Travelling.", lat: 15.4956, lng: 73.8315, tags: ["walking-tour", "food", "heritage"], price: "₹₹", timeToSpend: "1.5-2.5 hours", rating: 4.8, popularity: "high", bestTime: "Morning, Feb-Mar" },
      { name: "Divar Island Exploration", area: "Central", desc: "Ferry + guided walk/e-bike tour. Baroque churches, mangrove boat ride, feni tasting, local family lunch. Via Soul Travelling.", lat: 15.5120, lng: 73.8870, tags: ["ferry", "e-bike", "authentic-goa"], price: "₹₹", timeToSpend: "3-4 hours", rating: 4.7, popularity: "medium", bestTime: "3 PM start, Oct-Mar" },
      { name: "Mandovi River Sunset Cruise", area: "Central", desc: "Evening cruise on the Mandovi. Live Goan music, dance performances. Touristy but fun if you're into it.", lat: 15.5000, lng: 73.8300, tags: ["cruise", "sunset", "music"], price: "₹", timeToSpend: "1-2 hours", rating: 3.5, popularity: "high", bestTime: "Evening 6-7 PM, Oct-Mar" },
      { name: "Kaavi Art Workshop", area: "North", desc: "Learn ancient Goan wall art using laterite mud and natural dyes. Unique handcraft experience.", lat: 15.5600, lng: 73.7900, tags: ["art", "hands-on", "traditional"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Year-round, mornings" },
      { name: "Goan Cooking Class", area: "Various", desc: "Multiple operators offer home-cooking classes. Learn Vindaloo, Xacuti, Bebinca from local families.", lat: 15.4950, lng: 73.8300, tags: ["cooking", "hands-on", "take-home-recipes"], price: "₹₹", timeToSpend: "3-4 hours", rating: 4.8, popularity: "high", bestTime: "Morning or evening, Oct-Mar" },
      { name: "Azulejo Tile Painting Workshop", area: "Central", desc: "Learn traditional Portuguese-Goan tile painting at a heritage house. Create your own hand-painted azulejo tile to take home.", lat: 15.4969, lng: 73.8278, tags: ["workshop", "art", "portuguese-heritage", "hands-on"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.7, popularity: "low", bestTime: "Year-round, book ahead" },
      { name: "Traditional Fishing with Local Fishermen", area: "South", desc: "Join local ramonkar fishermen in Betalbatim for authentic fishing. Learn traditional techniques, help haul nets. Morning catch followed by fresh seafood meal.", lat: 15.2932, lng: 73.9078, tags: ["fishing", "local-culture", "authentic", "village-life"], price: "₹₹", timeToSpend: "3-4 hours", rating: 4.6, popularity: "low", bestTime: "Morning, Oct-May" },
      { name: "Pottery Workshop at Mati Earth", area: "North", desc: "Hands-on pottery with Goa's red laterite earth at this sustainable art studio in Mandrem. Single sessions to multi-day courses.", lat: 15.6850, lng: 73.7250, tags: ["pottery", "workshop", "art", "sustainability"], price: "₹₹", timeToSpend: "2-4 hours", rating: 4.8, popularity: "low", bestTime: "Oct-May, Tuesdays closed" },
      { name: "Bhagwan Mahavir Wildlife Sanctuary Birdwatching", area: "Central", desc: "Guided birdwatching through Goa's largest wildlife sanctuary in the Western Ghats. 200+ bird species including Malabar pied hornbill.", lat: 15.3500, lng: 74.2167, tags: ["birdwatching", "wildlife", "nature", "trekking"], price: "₹₹", timeToSpend: "Half day to full day", rating: 4.6, popularity: "medium", bestTime: "Nov-Apr" },
      { name: "Traditional Toddy Tapping Demonstration", area: "South", desc: "Witness ancient art of toddy tapping as skilled rendiers climb coconut trees to harvest sap for feni. Includes tasting of fresh toddy and coconut feni.", lat: 15.2500, lng: 73.9800, tags: ["feni", "local-tradition", "demonstration", "coconut"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Morning or evening, year-round" },
    ]
  },

  water: {
    icon: "🤿",
    title: "Water Activities",
    color: "#0284C7",
    items: [
      { name: "Scuba Diving at Grande Island", area: "South", desc: "Suzy's Wreck, Shelter Cove, Bounty Bay. 5-12m depth. See barracuda, rays, pufferfish. PADI certified operators.", lat: 15.3740, lng: 73.8470, tags: ["wreck-dive", "PADI", "beginners-ok"], price: "₹₹₹", timeToSpend: "Half day (4-5 hours)", rating: 4.5, popularity: "high", bestTime: "Oct-May, morning" },
      { name: "Scuba Diving at Bat Island", area: "South", desc: "Best coral reefs in Goa. Deeper dives (10-18m). Turtles, rays, moray eels. For intermediate+.", lat: 15.3650, lng: 73.8350, tags: ["coral", "advanced", "turtles"], price: "₹₹₹", timeToSpend: "Half day (4-5 hours)", rating: 4.4, popularity: "medium", bestTime: "Oct-May, morning" },
      { name: "Sal Backwaters Kayaking", area: "South", desc: "2-hour kayak through mangroves. Otters, kingfishers, lotus ponds. Serene and beautiful. Multiple operators.", lat: 15.2700, lng: 73.9600, tags: ["kayaking", "mangroves", "otters"], price: "₹₹", timeToSpend: "1.5-2.5 hours", rating: 4.8, popularity: "high", bestTime: "Early morning, Oct-May" },
      { name: "Chorao Island Kayaking", area: "Central", desc: "Mangrove kayaking + bird sanctuary visit. Spot crocodiles in winter. Peaceful alternative to South Goa kayaking.", lat: 15.5250, lng: 73.8780, tags: ["mangroves", "birds", "crocodiles"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.7, popularity: "high", bestTime: "High tide, early morning, Oct-Mar" },
      { name: "Dolphin Watching, Palolem", area: "South", desc: "Early morning boat trips. Very high success rate for sighting Humpback dolphins. Also visit Butterfly Beach.", lat: 15.0100, lng: 74.0230, tags: ["dolphins", "morning", "boat-trip"], price: "₹", timeToSpend: "1-2 hours", rating: 4.3, popularity: "high", bestTime: "Morning 7-8 AM, Oct-May" },
      { name: "Snorkeling at Grande Island", area: "South", desc: "Half-day trip including snorkeling, fishing, BBQ lunch on the boat. Good for non-divers.", lat: 15.3740, lng: 73.8470, tags: ["snorkeling", "BBQ", "half-day"], price: "₹₹", timeToSpend: "Half day (4-5 hours)", rating: 4.4, popularity: "high", bestTime: "Oct-May, morning" },
      { name: "Parasailing, Calangute/Baga", area: "North", desc: "Classic beach parasailing. Quick adrenaline hit. Negotiate prices, always check safety gear.", lat: 15.5440, lng: 73.7560, tags: ["parasailing", "adrenaline", "quick"], price: "₹₹", timeToSpend: "15-20 minutes", rating: 4.2, popularity: "high", bestTime: "Morning-afternoon, Oct-May" },
      { name: "Jet Skiing, Baga Beach", area: "North", desc: "Available at most North Goa beaches. 10-15 min rides. Negotiate hard, prices vary wildly.", lat: 15.5560, lng: 73.7510, tags: ["jet-ski", "negotiate", "fun"], price: "₹₹", timeToSpend: "10-15 minutes", rating: 4.0, popularity: "high", bestTime: "Morning-afternoon, Oct-May" },
      { name: "White Water Rafting, Mandovi River", area: "Central", desc: "During monsoon season (Jul-Sep). Grade II-III rapids near Valpoi. Seasonal adventure.", lat: 15.5300, lng: 74.1400, tags: ["monsoon-only", "rapids", "adventure"], price: "₹₹", timeToSpend: "1.5 hours", rating: 3.8, popularity: "medium", bestTime: "Monsoon (Jun-Oct)" },
      { name: "Moonlight Kayaking at Nerul River", area: "North", desc: "Paddle through mangrove-lined Nerul River under starlight. Bioluminescent plankton during new moon periods. Peaceful alternative to daytime tours.", lat: 15.5500, lng: 73.7620, tags: ["kayaking", "night-activity", "bioluminescence", "romantic"], price: "₹₹", timeToSpend: "1.5-2 hours", rating: 4.7, popularity: "low", bestTime: "Evening 6:30-7 PM, new moon for bioluminescence" },
      { name: "Canyoning at Netravali Waterfall", area: "Central", desc: "Rappelling, cliff jumping into natural pools, river gorge walking in Netravali Wildlife Sanctuary. Full safety equipment provided.", lat: 15.1800, lng: 74.1500, tags: ["canyoning", "rappelling", "adventure", "waterfall"], price: "₹₹₹", timeToSpend: "Half day to full day", rating: 4.8, popularity: "low", bestTime: "Oct-May (post-monsoon)" },
      { name: "Kayaking at Cola Beach Lagoon", area: "South", desc: "Explore the hidden freshwater lagoon behind Cola Beach, surrounded by volcanic boulders and lush hills. One of Goa's most secluded spots.", lat: 15.0400, lng: 74.0100, tags: ["kayaking", "hidden-beach", "lagoon", "peaceful"], price: "₹", timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Oct-Mar, morning or late afternoon" },
      { name: "Stand-Up Paddleboarding at Kalacha Beach", area: "North", desc: "SUP on the sweet water lake behind Kalacha Beach near Arambol. Natural spring-fed freshwater lake, calm conditions ideal for beginners.", lat: 15.6950, lng: 73.7050, tags: ["SUP", "lake", "hidden-gem", "paragliding"], price: "₹", timeToSpend: "1-2 hours", rating: 4.4, popularity: "low", bestTime: "Morning or evening, Oct-Apr" },
    ]
  },

  waterfalls: {
    icon: "💧",
    title: "Waterfalls",
    color: "#06B6D4",
    items: [
      { name: "Dudhsagar Falls", area: "East", desc: "5th tallest in India (310m). 'Sea of Milk'. Accessible by jeep through jungle. Swim in the pool below. Best Jul-Dec.", lat: 15.3144, lng: 74.3143, tags: ["must-visit", "jeep-ride", "swimming"], price: "₹₹", timeToSpend: "Half day (4-5 hours)", rating: 4.7, popularity: "high", bestTime: "Oct-Apr, just after monsoon for full flow" },
      { name: "Tambdi Surla Waterfall", area: "East", desc: "Near Goa's oldest temple (12th century Mahadev Temple). Gentle falls, jungle trek. Less crowded.", lat: 15.3900, lng: 74.2700, tags: ["temple-nearby", "trek", "quiet"], price: "Free", timeToSpend: "2-3 hours", rating: 4.4, popularity: "medium", bestTime: "Monsoon-Oct (Jul-Oct), combine with temple" },
      { name: "Arvalem (Harvalem) Waterfalls", area: "North", desc: "Near Arvalem Caves (Buddhist rock-cut caves). Easy access by road. Impressive during monsoon.", lat: 15.4800, lng: 74.0500, tags: ["caves-nearby", "easy-access", "monsoon"], price: "Free", timeToSpend: "1-2 hours", rating: 4.0, popularity: "medium", bestTime: "Monsoon-Dec (Jun-Dec), morning" },
      { name: "Netravali Waterfall (Savri)", area: "South", desc: "In the Netravali Wildlife Sanctuary. 'Bubbling Lake' nearby. Trek through forest. Off-beat.", lat: 15.1400, lng: 74.1800, tags: ["wildlife", "trek", "off-beat"], price: "₹", timeToSpend: "2-3 hours with trek", rating: 4.5, popularity: "medium", bestTime: "Sep-Feb, post-monsoon" },
      { name: "Hivre Waterfall", area: "East", desc: "Hidden gem near Valpoi. Requires a short trek. Crystal clear water. Almost no tourists.", lat: 15.4500, lng: 74.1800, tags: ["hidden", "trek", "crystal-clear"], price: "Free", timeToSpend: "3-4 hours", rating: 4.6, popularity: "low", bestTime: "Jul-Sep monsoon, experienced trekkers" },
      { name: "Kuskem Waterfall", area: "South", desc: "Secluded 30-meter high waterfall at entrance of Cotigao Wildlife Sanctuary. Hidden deep in pristine forests with minimal tourist footfall.", lat: 15.009, lng: 74.112, tags: ["secluded", "wildlife-sanctuary", "pristine", "hidden"], timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Jul-Oct monsoon and post-monsoon" },
      { name: "Charavane Waterfall", area: "North", desc: "Hidden gem deep within Mhadei Wildlife Sanctuary, accessible via scenic forest trail. Mesmerizing volume post-monsoon. 12km from Valpoi.", lat: 15.451, lng: 74.084, tags: ["wildlife-sanctuary", "trekking", "scenic", "pristine"], timeToSpend: "3-4 hours with trek", rating: 4.6, popularity: "low", bestTime: "Sep-Dec post-monsoon" },
      { name: "Mainapi Waterfall", area: "South", desc: "Beautiful cascade in Netravali Wildlife Sanctuary. Requires 4.85km trek through protected forest with exotic birds, butterflies, and rare plants.", lat: 15.150, lng: 74.168, tags: ["wildlife-sanctuary", "trekking", "birdwatching", "pristine"], timeToSpend: "3-4 hours with trek", rating: 4.4, popularity: "low", bestTime: "Jul-Nov monsoon to post-monsoon" },
      { name: "Bamanbudo Waterfall", area: "South", desc: "Charming roadside waterfall near Canacona. Two-three stepped cascade with shallow plunge pool. Accessible without hiking. Family-friendly.", lat: 15.058, lng: 74.146, tags: ["roadside", "family-friendly", "easy-access", "multi-tier"], timeToSpend: "30 mins - 1 hour", rating: 4.0, popularity: "low", bestTime: "Jul-Dec monsoon to post-monsoon" },
      { name: "Surla Waterfall", area: "East", desc: "50-meter zigzag cascade near Chorla Ghat in Mahdei Wildlife Sanctuary. Crystal clear pool at base ideal for swimming.", lat: 15.416, lng: 74.154, tags: ["swimming", "wildlife-sanctuary", "crystal-clear", "scenic"], timeToSpend: "2-3 hours", rating: 4.5, popularity: "low", bestTime: "Oct-Feb post-monsoon to winter" },
      { name: "Kesarval Waterfall", area: "South", desc: "Serene spring waterfall near Cortalim on Verna plateau. Just 22km from Panjim, easily accessible yet peaceful. Natural spring creates year-round flow.", lat: 15.382, lng: 73.992, tags: ["spring-fed", "accessible", "peaceful", "year-round"], timeToSpend: "1-2 hours", rating: 4.2, popularity: "low", bestTime: "Oct-Mar, flows year-round" },
    ]
  },

  markets: {
    icon: "🛒",
    title: "Markets",
    color: "#84CC16",
    items: [
      { name: "Mapusa Friday Market", area: "North", desc: "Biggest local market. Fresh fish, Goan sausage (choris), spices, local produce. Chaotic, authentic. Go early.", lat: 15.5884, lng: 73.8128, tags: ["friday", "authentic", "sausages"], price: "₹", timeToSpend: "1-2 hours", rating: 4.4, popularity: "high", bestTime: "Friday 8-11am to avoid crowds" },
      { name: "Anjuna Flea Market", area: "North", desc: "Wednesday afternoons. Hippie-era tradition. Clothes, jewelry, crafts, some overpriced tourist stuff. Bargain hard.", lat: 15.5730, lng: 73.7400, tags: ["wednesday", "hippie", "crafts"], price: "₹", timeToSpend: "2-3 hours", rating: 4.2, popularity: "high", bestTime: "Wednesday morning 9-11am, Nov-Apr" },
      { name: "Arpora Saturday Night Market", area: "North", desc: "Live music, food stalls, shopping. More curated than Anjuna. Good vibe for evening browsing.", lat: 15.5690, lng: 73.7660, tags: ["saturday-night", "music", "food-stalls"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.3, popularity: "high", bestTime: "Saturday 6pm-1am, Nov-Apr" },
      { name: "Margao Municipal Market", area: "South", desc: "South Goa's main market. Huge fish section, spice traders, local sweets. More intense than Mapusa.", lat: 15.2830, lng: 73.9570, tags: ["fish-market", "spices", "south-goa"], price: "₹", timeToSpend: "1-2 hours", rating: 4.0, popularity: "high", bestTime: "Weekday morning 9-11am" },
      { name: "Panjim Municipal Market", area: "Central", desc: "Compact city market. Fresh produce, flowers, fish. Near Fontainhas. Quick morning visit.", lat: 15.4980, lng: 73.8270, tags: ["compact", "morning", "flowers"], price: "₹", timeToSpend: "1-2 hours", rating: 3.9, popularity: "high", bestTime: "Morning 8am-1pm for fresh produce" },
      { name: "Quepem Sunday Market", area: "South", desc: "Authentic local Sunday bazaar. Fresh locally-grown vegetables, fruits, spices, traditional produce. Zero tourist crowds, real glimpse into daily Goan life.", lat: 15.2117, lng: 74.0808, tags: ["local", "traditional", "sunday", "authentic"], price: "₹", timeToSpend: "1 hour", rating: 4.0, popularity: "low", bestTime: "Sunday morning 8am-12pm" },
      { name: "Mackie's Saturday Night Market (Baga)", area: "North", desc: "Vibrant night bazaar near Baga beach. Clothing, souvenirs, live music by local bands, dance floor, artisans. Nov-Apr.", lat: 15.5569, lng: 73.7517, tags: ["nightmarket", "shopping", "music", "entertainment"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.2, popularity: "medium", bestTime: "Saturday 6pm-midnight, Nov-Apr" },
      { name: "Ashwem Beach Market", area: "North", desc: "Bohemian Wednesday evening market. High-end fashion, handmade jewelry, organic products. Less crowded than Anjuna. Oct-Apr.", lat: 15.6917, lng: 73.7144, tags: ["beachmarket", "bohemian", "jewelry", "organic"], price: "₹₹", timeToSpend: "2 hours", rating: 4.3, popularity: "low", bestTime: "Wednesday evening 5-8pm, Oct-Apr" },
      { name: "Goa Collective Bazaar (HillTop Vagator)", area: "North", desc: "Contemporary Friday evening bazaar at HillTop during peak season. Local designers, unique fashion, live bands and DJs under palm trees.", lat: 15.6000, lng: 73.7397, tags: ["contemporary", "designers", "music", "friday"], price: "₹₹", timeToSpend: "2-3 hours", rating: 4.4, popularity: "medium", bestTime: "Friday 6pm onwards, Nov-Feb" },
    ]
  },

  souvenirs: {
    icon: "🎁",
    title: "Souvenirs",
    color: "#F472B6",
    items: [
      { name: "Hand-Painted Azulejo Tiles", area: "Central", desc: "Portuguese-style ceramic tiles with Goan motifs. Buy at Velha Goa Galeria or Sunaparanta.", lat: 15.4909, lng: 73.8278, tags: ["art", "Portuguese", "ceramic"], price: "₹₹", shelfLife: null, timeToSpend: "30-45 mins", rating: 4.7, popularity: "high", bestTime: "Anytime during business hours (10am-7pm Mon-Sat)" },
      { name: "Velha Goa Galeria (Tile Shop)", area: "Central", desc: "Main azulejo tile workshop and gallery. Watch artisans paint tiles. Custom orders available.", lat: 15.4980, lng: 73.8280, tags: ["workshop", "tiles", "gallery"], price: "₹₹", shelfLife: null, timeToSpend: "30-60 mins", rating: 4.6, popularity: "high", bestTime: "Morning for browsing workshop, avoid lunch break 1:30-2pm" },
      { name: "Mario Miranda Merch", area: "Various", desc: "Prints, coasters, bags featuring iconic Goan cartoonist's art. Available at galleries and tourist shops.", lat: 15.5440, lng: 73.7680, tags: ["art", "cartoons", "prints"], price: "₹₹", shelfLife: null, timeToSpend: "20-30 mins", rating: 4.4, popularity: "high", bestTime: "Anytime (multiple locations in Calangute/Carmona)" },
      { name: "Seashell Crafts & Jewelry", area: "Various", desc: "Handmade shell necklaces, wind chimes, decorations. Best from beach vendors and flea markets.", lat: 15.5730, lng: 73.7400, tags: ["beach", "handmade", "jewelry"], price: "₹", shelfLife: null, timeToSpend: "15-30 mins", rating: 4.0, popularity: "high", bestTime: "Morning at beach markets or Anjuna Flea Market (Wednesday)" },
      { name: "Coconut Shell Crafts", area: "Various", desc: "Carved coconut shell lamps, bowls, spoons. Eco-friendly and uniquely Goan.", lat: 15.5884, lng: 73.8128, tags: ["eco", "handmade", "carved"], price: "₹", shelfLife: null, timeToSpend: "15-20 mins", rating: 3.8, popularity: "medium", bestTime: "Morning at local markets (Mapusa Friday, Anjuna Wednesday)" },
      { name: "Goan Cashew Nuts (Flavored)", area: "Various", desc: "Roasted, salted, masala, chocolate-coated. Airport-quality at market prices from local shops.", lat: 15.4909, lng: 73.8278, tags: ["food", "cashew", "snack"], price: "₹₹", shelfLife: "3-6 months", timeToSpend: "10-15 mins", rating: 4.8, popularity: "high", bestTime: "Anytime at shops, or visit cashew factory during season (Feb-May)" },
      { name: "Bebinca (Boxed)", area: "Various", desc: "Seven-layer Goan dessert. Boxed versions from Simonia's or local bakeries travel well.", lat: 15.2830, lng: 73.9570, tags: ["food", "dessert", "traditional"], price: "₹₹", shelfLife: "5-7 days", timeToSpend: "10-20 mins", rating: 4.5, popularity: "high", bestTime: "Morning for fresh stock at Simonia's or local bakeries" },
      { name: "Dodol", area: "Various", desc: "Sticky coconut jaggery fudge. Traditional Christmas sweet but available year-round.", lat: 15.2830, lng: 73.9570, tags: ["food", "sweet", "coconut"], price: "₹", shelfLife: "2-3 weeks", timeToSpend: "10-15 mins", rating: 4.2, popularity: "medium", bestTime: "Morning at traditional sweet shops" },
      { name: "Goan Sausage Strings (Choris)", area: "Various", desc: "Spiced pork sausages. Vacuum-packed for travel. Get from Mapusa Market or local butchers.", lat: 15.5884, lng: 73.8128, tags: ["food", "meat", "spiced"], price: "₹₹", shelfLife: "1-2 weeks refrigerated", timeToSpend: "10-15 mins", rating: 4.4, popularity: "medium", bestTime: "Morning at Mapusa Market (Friday) or local butcher shops" },
      { name: "Cashew Feni (Bottle)", area: "Various", desc: "Goa's signature spirit. Get Cazulo Premium or Big Boss. Legal to carry within India.", lat: 15.4909, lng: 73.8278, tags: ["drink", "feni", "spirit"], price: "₹₹", shelfLife: "Indefinite", timeToSpend: "15-30 mins", rating: 4.6, popularity: "high", bestTime: "Anytime, or visit distillery during season (Feb-May) for tours" },
      { name: "Urrak (Cashew Brew)", area: "Various", desc: "First distillation of cashew feni. Lighter, seasonal. Only available summer months.", lat: 15.4909, lng: 73.8278, tags: ["drink", "cashew", "seasonal"], price: "₹", shelfLife: "2-3 months", timeToSpend: "15-20 mins", rating: 4.3, popularity: "medium", bestTime: "Summer months only (seasonal availability)" },
      { name: "Goan Spice Mixes / Masalas", area: "Various", desc: "Recheado, xacuti, vindaloo, cafreal masala pastes. Fresh-ground at Mapusa Market.", lat: 15.5884, lng: 73.8128, tags: ["food", "spices", "cooking"], price: "₹", shelfLife: "3-6 months", timeToSpend: "15-25 mins", rating: 4.5, popularity: "high", bestTime: "Morning at Mapusa Market (Friday) or spice plantation shops" },
      { name: "Kokum Syrup / Agal", area: "Various", desc: "Tangy-sweet concentrate for sol kadhi and drinks. Digestive properties. Lightweight souvenir.", lat: 15.4909, lng: 73.8278, tags: ["drink", "kokum", "healthy"], price: "₹", shelfLife: "6-12 months", timeToSpend: "10-15 mins", rating: 4.4, popularity: "medium", bestTime: "Anytime at local shops or Mapusa Market" },
      { name: "Goan Coconut Oil (Cold-Pressed)", area: "Various", desc: "Pure cold-pressed coconut oil. Hair, skin, cooking. Distinctive Goan aroma.", lat: 15.4909, lng: 73.8278, tags: ["beauty", "cooking", "organic"], price: "₹", shelfLife: "12-18 months", timeToSpend: "10-15 mins", rating: 4.6, popularity: "medium", bestTime: "Anytime at local shops or organic stores" },
      { name: "Local Pottery & Terracotta", area: "Various", desc: "Red laterite clay pots, lamps, figurines. From Bicholim and Mapusa artisan villages.", lat: 15.5884, lng: 73.8128, tags: ["art", "clay", "handmade"], price: "₹", shelfLife: null, timeToSpend: "20-40 mins", rating: 4.2, popularity: "medium", bestTime: "Morning at artisan villages or Mapusa Market (Friday)" },
      { name: "Crochet & Lace Work", area: "Various", desc: "Intricate hand-crocheted tablecloths, doilies, dresses. Portuguese-era tradition kept alive.", lat: 15.4909, lng: 73.8278, tags: ["textile", "handmade", "Portuguese"], price: "₹₹", shelfLife: null, timeToSpend: "30-60 mins", rating: 4.3, popularity: "medium", bestTime: "Anytime at specialty shops in Panjim or local markets" },
      { name: "Cashew Marzipan / Goan Sweets", area: "Various", desc: "Marzipan made with cashews instead of almonds. Christmas tradition. Also try perad (guava cheese).", lat: 15.4909, lng: 73.8278, tags: ["food", "sweet", "Christmas"], price: "₹", shelfLife: "2-4 weeks", timeToSpend: "10-20 mins", rating: 4.5, popularity: "high", bestTime: "Morning for fresh sweets at traditional bakeries" },
      { name: "Literati Bookshop Goa", area: "North", desc: "Independent bookstore in Calangute. Goa-focused books, maps, art prints. Curated collection.", lat: 15.5440, lng: 73.7680, tags: ["books", "culture", "art"], price: "₹₹", shelfLife: null, timeToSpend: "45 mins - 2 hours", rating: 4.6, popularity: "medium", bestTime: "Anytime (closed Mondays, open until 6:30pm)" },
      { name: "Brass & Copper Church Bells (Miniature)", area: "Various", desc: "Replica church bells and religious artifacts. Unique Goan-Catholic keepsake.", lat: 15.4909, lng: 73.8278, tags: ["religious", "brass", "heritage"], price: "₹₹", shelfLife: null, timeToSpend: "15-30 mins", rating: 4.1, popularity: "low", bestTime: "Morning at Mapusa Market or handicraft emporiums in Panjim" },
      { name: "Coconut Vinegar (Toddy Vinegar)", area: "Various", desc: "Fermented coconut toddy vinegar. Key ingredient in vindaloo and sorpotel. Unique to Goa.", lat: 15.5884, lng: 73.8128, tags: ["food", "vinegar", "cooking"], price: "₹", shelfLife: "12+ months", timeToSpend: "10-15 mins", rating: 4.0, popularity: "low", bestTime: "Anytime at local grocery shops or markets" },
      { name: "Kunbi Sarees (Heritage Handloom)", area: "Central", desc: "Traditional cotton checkered sarees in deep red and white worn by the indigenous Kunbi tribe. Hand-embroidered designs inspired by local flora and Goan architecture. A beautiful piece of Goan textile heritage being revived by local designers.", lat: 15.4909, lng: 73.8278, tags: ["heritage", "textiles", "handloom", "traditional", "artisan"], price: "₹₹₹", shelfLife: null, timeToSpend: "30-45 mins", rating: 4.5, popularity: "low", bestTime: "Visit boutiques in Panjim or Assagao, anytime" },
      { name: "Samai (Brass Oil Lamps)", area: "North", desc: "Elegant tree-like brass oil lamps with intricate flower motifs, handcrafted in Corlim near Mapusa. Considered Goa's most famous handicraft. Stunning decorative piece or functional oil lamp.", lat: 15.5984, lng: 73.8149, tags: ["brass", "traditional", "handicraft", "artisan", "decorative"], price: "₹₹", shelfLife: null, timeToSpend: "20-30 mins", rating: 4.6, popularity: "low", bestTime: "Visit Mapusa Market on Friday mornings or Corlim workshops" },
      { name: "Wild Forest Honey (Sustainable Harvest)", area: "Various", desc: "Authentic wild honey harvested by tribal communities from the Sahyadri Ranges using sustainable indigenous methods. Rich complex flavors from native flowering trees. Each batch unique.", lat: 15.2993, lng: 74.1240, tags: ["honey", "organic", "sustainable", "tribal", "wild"], price: "₹₹₹", shelfLife: "24 months", timeToSpend: "15-20 mins", rating: 4.7, popularity: "low", bestTime: "Anytime at organic stores or farmers markets" },
      { name: "Bamboo & Palm Leaf Handicrafts", area: "Various", desc: "Eco-friendly artisan products woven from bamboo and palm leaves. Baskets, bags, mats, pen stands colored with vibrant natural paints. Traditional Goan weaving techniques.", lat: 15.4909, lng: 73.8278, tags: ["bamboo", "eco-friendly", "sustainable", "handicraft"], price: "₹", shelfLife: null, timeToSpend: "20-40 mins", rating: 4.1, popularity: "low", bestTime: "Mapusa Market Friday mornings or artisan villages in Bicholim" },
      { name: "Paper Boat Collective Artisan Goods", area: "North", desc: "Curated handcrafted sustainable products in a 100-year-old Portuguese villa in Assagao. Independent artisan work in cotton, bamboo, khadi, jute, hemp. Experience-led concept store.", lat: 15.5977, lng: 73.7622, tags: ["artisan", "sustainable", "eco-friendly", "boutique", "handmade"], price: "₹₹₹", shelfLife: null, timeToSpend: "45 mins - 1.5 hours", rating: 4.8, popularity: "low", bestTime: "Anytime during business hours, weekdays less crowded" },
    ]
  },

  highs: {
    icon: "🍹",
    title: "Drinks & Highs",
    color: "#A855F7",
    items: [
      { name: "Cashew Feni (Cazulo Premium)", area: "South", desc: "Triple-distilled premium feni from Curchorem. Smooth, aromatic. Gold standard of feni.", lat: 15.2500, lng: 74.1000, tags: ["feni", "premium", "local"], price: "₹₹₹", timeToSpend: "30 mins - 1 hour", rating: 4.7, popularity: "medium", bestTime: "Visit distillery for tasting during season (Feb-May)" },
      { name: "Cashew Feni (Big Boss)", area: "Various", desc: "Most popular feni brand. Available everywhere. Good entry-level feni experience.", lat: 15.4909, lng: 73.8278, tags: ["feni", "popular", "local"], price: "₹", timeToSpend: "15-30 mins", rating: 4.5, popularity: "high", bestTime: "Anytime at local liquor shops" },
      { name: "Coconut Feni (Toddy Feni)", area: "Various", desc: "Made from coconut toddy instead of cashew. Different flavor profile. Less common.", lat: 15.4909, lng: 73.8278, tags: ["feni", "coconut", "traditional"], price: "₹", timeToSpend: "15-30 mins", rating: 4.2, popularity: "medium", bestTime: "Anytime at local distilleries or liquor shops" },
      { name: "Dukshiri Feni", area: "Various", desc: "Small-batch artisan feni. Smoky, complex flavors from traditional copper pot distillation.", lat: 15.4909, lng: 73.8278, tags: ["feni", "artisan", "small-batch"], price: "₹₹", timeToSpend: "20-30 mins", rating: 4.3, popularity: "low", bestTime: "Anytime at specialty feni shops or distilleries" },
      { name: "Urrak", area: "Various", desc: "First distillation of cashew apple juice. Lighter than feni (~15-30% ABV). Summer-only seasonal drink.", lat: 15.4909, lng: 73.8278, tags: ["cashew", "seasonal", "light"], price: "₹", timeToSpend: "15-20 mins", rating: 4.4, popularity: "medium", bestTime: "Summer only (seasonal, first distillation)" },
      { name: "Urrak + Limca Combo", area: "Various", desc: "Classic Goan summer cooler. Urrak mixed with Limca soda. Refreshing afternoon drink.", lat: 15.4909, lng: 73.8278, tags: ["cocktail", "summer", "refreshing"], price: "₹", timeToSpend: "10-15 mins", rating: 4.0, popularity: "medium", bestTime: "Summer afternoons at local bars" },
      { name: "Feni Cocktails at Joseph Bar", area: "Central", desc: "Legendary feni cocktails at Goa's oldest taverna in Fontainhas. Try Tambde Rosa (rose feni cocktail).", lat: 15.4989, lng: 73.8313, tags: ["cocktails", "feni", "heritage"], price: "₹₹", timeToSpend: "1-2 hours", rating: 4.8, popularity: "high", bestTime: "12 noon sharp to avoid 1-hour wait" },
      { name: "Port Wine (Goan Style)", area: "Various", desc: "Portuguese-influenced sweet fortified wine tradition. Local varieties available at heritage bars.", lat: 15.4909, lng: 73.8278, tags: ["wine", "Portuguese", "sweet"], price: "₹₹", timeToSpend: "20-30 mins", rating: 4.1, popularity: "low", bestTime: "Anytime at specialty bars or liquor shops in Panjim" },
      { name: "Paul John Single Malt Whisky", area: "South", desc: "World-class single malt distilled in Goa. Multiple international awards. Visit the distillery.", lat: 15.3833, lng: 73.8833, tags: ["whisky", "premium", "distillery"], price: "₹₹₹", timeToSpend: "30 mins - 1 hour", rating: 4.7, popularity: "medium", bestTime: "Evening tasting at premium bars or distillery shop" },
      { name: "Kings Beer", area: "Various", desc: "Goa's local beer. Light lager, cheap, available everywhere. The default beach beer.", lat: 15.4909, lng: 73.8278, tags: ["beer", "local", "light"], price: "₹", timeToSpend: "30 mins - 1 hour", rating: 3.8, popularity: "high", bestTime: "Anytime at bars and restaurants" },
      { name: "Toddy (Soor / Kallu)", area: "Various", desc: "Fresh coconut palm sap. Mildly alcoholic, slightly sweet. Drink within hours of tapping.", lat: 15.4909, lng: 73.8278, tags: ["toddy", "traditional", "palm"], price: "₹", timeToSpend: "30 mins - 1 hour", rating: 4.3, popularity: "medium", bestTime: "Early morning (fresh from toddy tappers)" },
      { name: "Kokum Feni Sour", area: "Various", desc: "Feni cocktail with kokum syrup and lime. Perfect balance of tart, sweet, and spirit.", lat: 15.4909, lng: 73.8278, tags: ["cocktail", "kokum", "feni"], price: "₹₹", timeToSpend: "30 mins - 1 hour", rating: 4.5, popularity: "medium", bestTime: "Evening at cocktail bars" },
      { name: "Cannabis (Bhang Lassi)", area: "North", desc: "Available at certain beach shacks in Anjuna/Vagator. Legal grey area. Use responsibly.", lat: 15.5750, lng: 73.7400, tags: ["bhang", "beach", "alternative"], price: "₹", timeToSpend: "1-3 hours", rating: 3.5, popularity: "medium", bestTime: "Afternoon at beach shacks in Anjuna/Vagator" },
      { name: "Mushroom Shakes", area: "North", desc: "Available seasonally at select beach shacks. Not legal. Proceed with caution.", lat: 15.5750, lng: 73.7400, tags: ["psychedelic", "seasonal", "alternative"], price: "₹", timeToSpend: "2-4 hours", rating: 3.2, popularity: "low", bestTime: "Afternoon at select beach shacks (seasonal)" },
      { name: "Cazulo Feni Tasting Flight", area: "South", desc: "Guided tasting at Cazulo distillery. Multiple feni varieties. Includes orchard walk and plantation meal.", lat: 15.2500, lng: 74.1000, tags: ["tasting", "distillery", "premium"], price: "₹₹₹", timeToSpend: "1-2 hours", rating: 4.8, popularity: "low", bestTime: "Book tour during season (Feb-May)" },
      { name: "Bebinca Cocktail (Specialty)", area: "Various", desc: "Dessert cocktail inspired by Goa's signature sweet. Cream, spice, and spirit layers.", lat: 15.4909, lng: 73.8278, tags: ["cocktail", "fusion", "dessert"], price: "₹₹₹", timeToSpend: "30 mins - 1 hour", rating: 4.2, popularity: "low", bestTime: "Evening at upscale bars featuring Goan fusion cocktails" },
      { name: "Stranger & Sons Craft Gin Tasting", area: "Various", desc: "Award-winning artisanal gin distilled in Goa with 9 Indian botanicals including Gondhoraj lemon. Aromatic citrus notes with warming liquorice and spicy undertones.", lat: 15.2993, lng: 74.1240, tags: ["gin", "craft", "local", "sustainable", "artisan"], price: "₹₹₹", timeToSpend: "30 mins - 1 hour", rating: 4.6, popularity: "low", bestTime: "Evening at craft cocktail bars (Titlie, Miguel's)" },
      { name: "Sol Kadhi (Traditional Digestive Drink)", area: "Various", desc: "Traditional Goan pink drink made from coconut milk and kokum. Cooling, aids digestion. Must-try authentic beverage rarely found outside the region.", lat: 15.2993, lng: 74.1240, tags: ["traditional", "healthy", "digestive", "authentic", "kokum"], price: "₹", timeToSpend: "15-20 mins", rating: 4.4, popularity: "low", bestTime: "After lunch at traditional Goan restaurants" },
      { name: "Kokum Mojito (Goan Fusion)", area: "Various", desc: "Local twist on the classic mojito with kokum syrup, white rum, mint, and lime. Distinctive purple-pink hue with digestive and cooling properties.", lat: 15.4909, lng: 73.8278, tags: ["cocktail", "fusion", "kokum", "refreshing"], price: "₹₹", timeToSpend: "45 mins - 1 hour", rating: 4.3, popularity: "low", bestTime: "Evening at sunset bars" },
      { name: "Goa Heritage Distillery Farm-to-Bottle Tour", area: "Various", desc: "Third-generation family distillery offering immersive cashew feni production tours. Witness complete farm-to-bottle process. Only available during cashew season (Feb 15 - May 31).", lat: 15.2993, lng: 74.1240, tags: ["tour", "distillery", "feni", "traditional", "heritage"], price: "₹₹₹", timeToSpend: "2-3 hours", rating: 4.9, popularity: "low", bestTime: "Morning slot 9:30 AM during season (Feb 15 - May 31)" },
      { name: "Titlie Signature Cocktails at Sunset", area: "North", desc: "Cliff-edge culinary bar at Ozran Beach with stunning sunset views. Expertly crafted cocktails using local spirits. One of Goa's most sought-after bars.", lat: 15.5994, lng: 73.7344, tags: ["cocktails", "sunset", "beach", "upscale", "views"], price: "₹₹₹", timeToSpend: "1.5-3 hours", rating: 4.7, popularity: "medium", bestTime: "Sunset hours (5:30-7:30 PM), arrive early for best seating" },
    ]
  },
};
